baseURL = 'https://sharkberry.me/'
locale = 'en-us'
title = '🦈🍓Sharkberry'
theme = 'somestyleplease'

[params.theme_config]
appearance = "matrix" # auto | light | dark | matrix | bear | together
categories = true
tags = true
post_limit = 100
show_more_url = "posts"
favicon = ""

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.en]
    date_format = "01.02.2006"
    locale = 'en-US'
    label = 'English'
    direction = 'ltr'
    title = '🦈🍓Sharkberry'
    weight = 1

  [languages.pt]
    date_format = "02.01.2006"
    locale = 'pt-BR'
    label = 'Português'
    direction = 'ltr'
    title = '🦈🍓Tubarão-Frutinha'
    weight = 2

[[languages.en.params.navbar_categories]]
  title = 'tech'
  url = '/categories/tech/'
  weight = 2

[[languages.en.params.navbar_categories]]
  title = 'thoughts'
  url = '/categories/thoughts/'
  weight = 3

[[languages.pt.params.navbar_categories]]
  title = 'tecnologia'
  url = '/categories/tecnologia/'
  weight = 2

[[languages.pt.params.navbar_categories]]
  title = 'pensamentos'
  url = '/categories/pensamentos/'
  weight = 3

[languages.en.params.homepage]
  [[languages.en.params.homepage.blocks]]
    enabled = true
    type = "category"
    category = "tech"
    limit = 5
    show_more_key = "showMoreTech"

  [[languages.en.params.homepage.blocks]]
    enabled = true
    type = "category"
    category = "thoughts"
    limit = 5
    show_more_key = "showMoreThoughts"

[languages.pt.params.homepage]
  [[languages.pt.params.homepage.blocks]]
    enabled = true
    type = "category"
    category = "tecnologia"
    limit = 100
    show_more_key = "showMoreTech"

  [[languages.pt.params.homepage.blocks]]
    enabled = true
    type = "category"
    category = "pensamentos"
    limit = 100
    show_more_key = "showMoreThoughts"